name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v7

      - name: Setup Go environment
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v9

      - name: Build
        shell: bash
        run: go build -v ./...

      - name: Test
        shell: bash
        run: go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          slug: ${{ github.repository }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
